version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: goodbooks-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: books
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - goodbooks-network

  api:
    build: .
    container_name: goodbooks-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: mongodb://localhost:27017/books
      DB_NAME: books
      API_KEY: dev-key
    depends_on:
      - mongodb
    networks:
      - goodbooks-network
    volumes:
      - ./app:/app/app
      - ./ingest:/app/ingest

  # Optional: MongoDB Express for database management
  mongo-express:
    image: mongo-express:1.0.0
    container_name: goodbooks-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
    depends_on:
      - mongodb
    networks:
      - goodbooks-network

volumes:
  mongodb_data:

networks:
  goodbooks-network:
    driver: bridge
